### ISSUE TITLE
please publish scala doc

### ISSUE THREAD

**Issue by johnynek** [buntec/ff4s#211]
This looks like a great library that I'm excited to try. One of the reasons I love typed functional programming is that the type signatures are often great documentation.

Would you be willing to publish the scala docs for this library so that we can easily see the types without having to click through the GitHub UI or checking the project out locally?

Thanks for your work on this!

**Comment by buntec** [comment]
Hi, thanks for your interest in the library! I think docs are already available [here](https://www.javadoc.io/doc/io.github.buntec). Is this what you are after?

**Comment by johnynek** [comment]
yes! I'm sorry. I didn't find those when I was looking at the main page or the documentation page. Did I miss it? Do you think we could add a more prominent link?

**Comment by johnynek** [comment]
Thank you!
