### ISSUE TITLE
Question about Store name

### ISSUE THREAD

**Issue by johnynek** [buntec/ff4s#220]
I'm enjoying using ff4s on a simple UI. I really enjoy programming with cats and pure functional style, so I appreciate your work on this.

I've shown this library to a few people and one place they always trip up is explaining with Store is named what it is. The main thing it seems to be about is the updating logic of `(Action, State) => State`. Or someone with more FP experience might notice that it something like `Action => cats.data.State[State, Option[IO[Unit]]`

I don't have a great suggestion for you, but I noticed you are still making incompatible changes, so I thought I would bring the issue up. Something more direct like Update, or maybe TransitionMatrix.

Just thought I would share my feedback.

**Comment by buntec** [comment]
The store terminology is entirely borrowed from [redux](https://redux.js.org/api/store). I don't have strong feelings about the naming, however, and I'm open to suggestions.

**Comment by buntec** [comment]
I've expanded on the scaladoc for the store.
